### ISSUE TITLE
Splitting messages containing a Discord context crashes node-red

### ISSUE THREAD

**Issue by jorisvddonk** [jorisvddonk/node-red-contrib-discord#1]
Consider the following node-red flow:

    [{"id":"60977b55.263584","type":"discordMessage","z":"24e609a3.ba51a6","name":"","token":"","x":227.5,"y":313,"wires":[["8e4f2b5f.6a0848","452d7834.7c4588"]]},{"id":"452d7834.7c4588","type":"function","z":"24e609a3.ba51a6","name":"","func":"\nreturn msg;","outputs":1,"noerr":0,"x":435.5,"y":337,"wires":[[]]},{"id":"8e4f2b5f.6a0848","type":"function","z":"24e609a3.ba51a6","name":"","func":"\nreturn msg;","outputs":1,"noerr":0,"x":430.5,"y":276,"wires":[[]]}]

With this flow active, whenever a message is received on Discord, node-red will crash with the following error:

    23 Jan 19:25:24 - TypeError: Method _external called on incompatible receiver #<SecureContext>
    at Function.getOwnPropertyDescriptor (<anonymous>)
    at _clone (C:\Users\joris\AppData\Roaming\npm\node_modules\node-red\node_modules\clone\clone.js:156:24)
    at _clone (C:\Users\joris\AppData\Roaming\npm\node_modules\node-red\node_modules\clone\clone.js:162:18)
    at _clone (C:\Users\joris\AppData\Roaming\npm\node_modules\node-red\node_modules\clone\clone.js:162:18)
    at _clone (C:\Users\joris\AppData\Roaming\npm\node_modules\node-red\node_modules\clone\clone.js:162:18)
    at _clone (C:\Users\joris\AppData\Roaming\npm\node_modules\node-red\node_modules\clone\clone.js:162:18)
    at _clone (C:\Users\joris\AppData\Roaming\npm\node_modules\node-red\node_modules\clone\clone.js:162:18)
    at _clone (C:\Users\joris\AppData\Roaming\npm\node_modules\node-red\node_modules\clone\clone.js:162:18)
    at _clone (C:\Users\joris\AppData\Roaming\npm\node_modules\node-red\node_modules\clone\clone.js:162:18)
    at _clone (C:\Users\joris\AppData\Roaming\npm\node_modules\node-red\node_modules\clone\clone.js:137:26)

**Comment by jorisvddonk** [comment]
This has been fixed for all nodes other than the deprecated discordClient node, and information has been added to the readme regarding usage of that node and this bug, so I feel that this bug can be closed.
